### PR TITLE
Build calculator UI

### PR DESCRIPTION
**Pull request by Ugboaja-Uchechi**
In this project, I created:

- A directory called components.
- Inside components, created a new Calculator.js file
- Develop just the UI of the calculator;

### CODE REVIEW

**Comment by Ugboaja-Uchechi** [comment]
Worked on the project requirements to the best of my knowledge.
All linter errors have passed.
No merge conflicts.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

 - [x] All the boilerplate that got created by the CRA (texts, images, and styles) ought to have gotten deleted.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Ugboaja-Uchechi** [comment]
Removed all unnecessary files suggested by my code reviewer.

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @Ugboaja-Uchechi, 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
